### PR TITLE
Add some getListener() functions

### PR DESCRIPTION
**Pull request by superquadratic**
I recently needed these getters, so I implemented them. A small step towards fixing moai/moai-dev#566. :)

### CODE REVIEW

**Comment by CircuitCipher** [comment]
This looks good.  We should keep making progress towards this as I see a lot of newcomers ask about why getters are missing.

@superquadratic Could you look into adding the same to the Android versions of the extensions you modified, please?  Should basically be the same code.  Thanks.

**Comment by superquadratic** [comment]
`setListener()` is copy-and-pasted in every Android singleton, so we will either have to do the same for `getListener()` (ugly) or refactor both to use `MOAIGlobalEventSource` (risky). Unfortunately I don't have the resources to implement and (more importantly) test either option.

**Comment by CircuitCipher** [comment]
Okay sounds good. We can address that at a later time.

**Comment by CircuitCipher** [comment]
Made a test file to test it out.  Looks good.  Thanks. I'll merge this in.

**Pull request merged**
