### PR TITLE
Rebase from community 140602

### PR DESCRIPTION
**Pull request by patrickmeehan**
Wow! Amazing job moving Moai forward, everyone! Wasn't sure what was going to happen when I went dark last fall but... you're still here! And have made huge progress! This is awesome. :)

I'm not sure I understand the moai-dev branches these days. So I created a new develop branch to collect breaky, broken stuff. The first batch of which is this massive rebase from my own moai-dev/develop.

Some notes:

1 - This is going to be broken. I just did the rebase and sent this pull request right away. I wanted to get this out there ASAP so people can start picking on it. It would be a big help if someone could grab this and tell me what needs fixing and/or fix it, especially on Android.

2 - I need to go over every prior commit and restore anything that got clobbered. MOAITextBox and MOAIShader got refactored (among others) so I'm guessing some stuff fell on the floor. If you can see right away that I missed something obvious, please let me know. I didn't intentionally remove anything.

3 - The IDE projects are back. Cmake is great but it doesn't meet my personal development needs. I will maintain the Xcode and VS projects myself, but they will break. A lot. You can (a) fix them or (b) wait for me to do it. If someone decides we need a release, just kick me and I'll make a point to get them working again. They are super easy to maintain, I just rarely touch both environments in the same day (or week).

4 - The Android stuff is missing the Java files that work with my new .cpp bindings. I need to grok the new build system then I will submit those. I dearly want to find a way to keep them under src/ with all the other source. Not a fan of the way they are buried under ant. So if you are using Android, know that this rebase clobbers it.

5 - The 3rd party stuff on iOS and Android is being used in my own projects right now. I'll be looking at each and checking them against the community version. I think I have the latest of each, but will make sure. I did change some of the APIs to bring them a bit closer to what I want to use. Sorry if that wrecks anyone.

6 - The vector drawing stuff was all funded by Point Inside. If you are wondering, yes, it's being used to render SVG. I decided to write the parser in Lua and will ask them if I can contribute a simplified version of it.

7 - The overlap stuff is nascent. The intent is to have a simple package for overlap detection and arcade-style games where using a full physics package is overkill. I just did the bare minimum for my current client project. It's already starting to push at how I want to think about MOAIProp and making it more extensible. I'll solicit your feedback Soon(tm). Just know that, for now, the overlap stuff is very preliminary and the facet pattern is just one idea I'm playing with.

That's it. I'll follow up with more fixes on this branch in the next few days.

### CODE REVIEW

**Comment by makotok** [comment]
Nice job!
I'm glad to come back!

Question. 
1. IDE project can be automatically generated by CMake. This method dissatisfaction?

./bin/create-projects-ios.sh
./bin/create-projects-osx.sh
./bin/create-projects-win.bat

**Comment by patrickmeehan** [comment]
Does the organization of the IDE projects it generates match my current IDE projects exactly?

**Comment by halfnelson** [comment]
They almost certainly won't. They might be massaged to get close but it probably isn't worth it. 

Hand crafted visual studio projects are always going to be nicer to work with. The downside is that the projects need to be maintained, but you have put your hand up for that :) (Thanks!)

I am happy to continue with the CMake support for xcode and visual studio as these aren't too hard to continue with now that they are setup, but hand written visual studio and xcode projects would probably be welcomed by anyone doing heavy development and debugging on the core moai libs. 

Time to see if all the work merging your last pull request paid off, hopefully this merge isn't as hard but since it has breaking changes, I suggest this be targeted at 1.6, and 1.5 can be moved to 1.5 development and 1.5 stable, master can be our 1.6 development branch.

Welcome back!

**Comment by makotok** [comment]
I synchronized the 1.5-stable branch and 1.5-development branch.
In addition, I have created a current tag.

Now, it is possible to merge in peace the pull request of Patrick.

**Comment by patrickmeehan** [comment]
It's good to be back! I'm still blown away by the quality the fixes and contributions. And by you guys for maintaining them! It's just awesome. :)

**Comment by halfnelson** [comment]
@makotok were you going to have a go at merging this or did you want me to do it?

**Comment by JDaance** [comment]
Welcome back! This is great news :)

As long as the cmake versions of VS and xcode are running by all means add the IDE projects back :) I love the cmake generated VS projects because they are always up to date and even include my own plugins (through halfnelsons awesome plugin system). But they do lack a lot in organization so I understand the need for dedicated projects.

**Comment by patrickmeehan** [comment]
@JDaance Thanks! And my thought as well. Cmake is is a great value. No reason the various projects and build schemes can't coexist.

**Pull request merged**
