### PR TITLE
Add capability to track a transform's position with MOAICameraFitter2D.

### PR DESCRIPTION
**Pull request by monomon**
Add an example too

### CODE REVIEW

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by ConghuZhao** [comment]
Test

**Comment by seclorum** [comment]
I've tested it locally, looks good to me.  @halfnelson, what say you?

**Comment by monomon** [comment]
I still have to provide a better example, because this one doesn't make it visually apparent what is happening.

**Comment by ConghuZhao** [comment]
hey @seclorum the build is tested on ci jenkins, and moai-sdk is the account for it. so any pull request made the moai-sdk will prompt admin which are patrick @seclorum @halfnelson and @makotok for approve, all you need to do is reply "test" on the pull request, this will kick off the build job on our build server. the result will be post on pull request like this

**Comment by seclorum** [comment]
@ConghuZhao Roger that!  I'm happy to see the CI build it, but I'm also willing to manually test/inspect these kinds of things before the PR gets merged .. this PR gets a thumbs-up from me on that angle, anyway.

**Comment by seclorum** [comment]
@monomon re:

> I still have to provide a better example, because this one doesn't make it visually apparent what is happening.

I think with DEBUG_LINES turned on, things are obvious no?

```
MOAIDebugLines.setStyle(MOAIDebugLines.PARTITION_CELLS, 2, 0, 0, 1, 1)
MOAIDebugLines.setStyle(MOAIDebugLines.PARTITION_PADDED_CELLS, 1, 0, 1, 0, 1)
MOAIDebugLines.setStyle(MOAIDebugLines.PROP_WORLD_BOUNDS, 2, 1, 0, 0, 1)
MOAIDebugLines.setStyle(MOAIDebugLines.PROP_MODEL_BOUNDS, 5, 1, 0.6, 0, 1)
--MOAIDebugLines.setStyle(MOAIDebugLines.TOTAL_STYLES, 2, 1, 1, 0, 1)

```

**Comment by monomon** [comment]
Thank you, it does become clearer. Committed the updated example.

**Comment by halfnelson** [comment]
Nice one, Thanks for the contribution

**Pull request merged**
