### PR TITLE
Pull cmake improvements

### PR DESCRIPTION
**Pull request by halfnelson**
Small fix to the doc generator's version parser
Improve visual studio support with and speed with parallel builds
Improve generated vs projects with solutions folders
fix curl build (needed zlib)
Clone sdl2 so we can edit the cmakelists.txt and added to solution folder

### CODE REVIEW

**Comment by makotok** [comment]
Thank you for fix.

**Comment by makotok** [comment]
This fix will I build error in the Windows environment?

http://getmoai.com/forums/error-building-vs-solution-via-cmake-t2531/

**Comment by DanielSWolf** [comment]
@makotok I'm not sure what you're asking. As I wrote on that forum thread, it seems to me that this pull request (#837) somehow introduced the problem.

**Comment by DanielSWolf** [comment]
Wrong alarm! The problem was actually caused by my virus scanner! Sorry about that!

**Comment by halfnelson** [comment]
no problems. Does it build faster for you and are you happy with folder layout?

**Comment by DanielSWolf** [comment]
Yes on both accounts! :-)

**Pull request merged**
