### PR TITLE
Apsalar renovations

### PR DESCRIPTION
**Pull request by ubershmekel**
Fixed android apsalar having nil mCanonicalUID as default, removed duplicate "&c=" on failure, print error code on failure.

### CODE REVIEW

**Comment by adamvillalobos** [comment]
I'm a little concenred with line "require "cloud-manager"" as I don't believe thats part of our default modules.

**Comment by ubershmekel** [comment]
What about all the cloud.encode lines? How do they work?

**Comment by adamvillalobos** [comment]
Ah, the cloud.encode needs to be changed to the url module. Those are a mistake. The rest of the changes are good, except for the one assigning a default Canonical UID. This should be given to you by apsalar, if its not, the services shouldn't be used.

**Comment by ubershmekel** [comment]
I see, thank you. And I have a bit of an OT question - the "DEVICE" global - it isn't something that MOAI sets but it seems to be used in many MOAI standard modules. Is there an alternative for that one as well?

**Comment by patrickmeehan** [comment]
Not planing to support Apsalar moving forward, so closing this.

**Pull request closed without merging**
