### PR TITLE
Enabling software synth with UNTZ, and adding recording class MOAIAudioSampler

### PR DESCRIPTION
**Pull request by kengonakajima**
Now you can 
- Create software synthesizer on moai UNTZ.
- Get audio samples by microphone on iOSes
# Software Synth

<pre>
local samplebuf = MOAIUntzSampleBuffer.new()
samplebuf:prepareBuffer( nChan, freq * totalLenSec , freq )

local data = {}
for i=1,10000 do
    data[i] = math.sin( i / 5 ) -- set wavedata from -1 to 1
end
samplebuf:setData( data,1 ) 
s = MOAIUntzSound.new()
s:load(samplebuf)
s:setVolume(1)
s:setLooping(true)
s:play()
</pre>

Of cource you can mix it with sounds from wav files.
# MOAIAudioSampler

<pre>
local sampler = MOAIAudioSampler.new()
sampler:setFrequency(44100)
sampler:setNumChannels(2)
sampler:prepareBuffer(0.2,10)
sampler:start()
thread:run( function() while true do
       local data = sampler:read()
       coroutine.yield()
    end
end)

</pre>

You can put the data from sampler to samplebuf:setData(), then it plays back the samples.

### CODE REVIEW

**Comment by kengonakajima** [comment]
this request is related to a forum article http://getmoai.com/forums/post1920.html#p1920

but this could also be useful for media artists or game creators.

**Comment by kengonakajima** [comment]
Today I've added MOAIAudioSampler so I can make VoIP on Moai games. (Should be careful with howling.)

**Comment by kengonakajima** [comment]
wow, super great! thank you for your effort.

**Comment by adamvillalobos** [comment]
Hope I got it right =p.

On Wed, Mar 14, 2012 at 11:31 PM, Kengo Nakajima <
reply@reply.github.com

**Comment by ggsonic** [comment]
hi will android devices be supported? or is it on your plan?

**Comment by frantufro** [comment]
Not right now, but you're welcome to contribute it!

**Pull request merged**
