### PR TITLE
updated box2d physics sample

### PR DESCRIPTION
**Pull request by mx1up**
hi,

I tried the chipmunk physics sample and was disappointed to not find similar functionality in the box2d sample. The thing is I struggled a bit to get the mouse joint working, so I guess it could be useful to include in the sample how to manipulate an object. What do you think?

this is the first time I do a pull request, so please bear with me if I did stupid things :)

greets
matthias

### CODE REVIEW

**Comment by frantufro** [comment]
Hi!! Thanks a lot for contributing!!
I'd need you to take a look at http://getmoai.com/contributors/ and send us the contributor agreement so I can merge this pull request.

Hope to hear from you soon and have you collaborating!!!

Thanks!

**Comment by chris-allnutt** [comment]
@franciscotufro that link is broken.  @mxttie this one does work tho http://getmoai.com/open-source-contributions.html

**Comment by frantufro** [comment]
Forget about it. We removed that requirement.
Thanks Chris for reporting that, but we'll not requesting this anymore. 

I'll take a look at the sample and merge it if everything is ok soon.

**Comment by mx1up** [comment]
great!

**Pull request merged**
