### PR TITLE
Create a shared interface, MOAIBrowser for opening urls across platforms

### PR DESCRIPTION
**Pull request by CircuitCipher**
Addresses issue #514 by doing the following:
- Move MOAISafariIOS to MOAIBrowserIOS
- Move MOAIAppAndroid::openURL to the newly created MOAIBrowserAndroid class
- Add openURLWithParams to Android

This PR also addresses PR #413 by adding the method canOpenURL to both platforms.

Please close both of these tickets when merging this PR.  Thanks!

### CODE REVIEW

**Comment by makotok** [comment]
Amazing! I will test for a while.

**Comment by CircuitCipher** [comment]
@makotok Okay, great!  If you didn't know already, you can use this to try out the pull request locally: https://help.github.com/articles/checking-out-pull-requests-locally

**Comment by makotok** [comment]
I added the sample.
Also, I have modified compatibility.

To merge.

**Comment by CircuitCipher** [comment]
Great.  Excellent compatibility code.  Thanks for your additions.

**Pull request merged**
