### PR TITLE
Add LuaJIT Support to Android Host

### PR DESCRIPTION
**Pull request by CircuitCipher**
- Add build script for cross compiling LuaJIT for Android
- Add LuaJIT options in the make-host script
- Add LuaJIT compilation step to libmoai build script
- Add LuaJIT to ndk make files
- Update init.lua varargs usage

### CODE REVIEW

**Comment by makotok** [comment]
The following error when you build in Android.

```
==== Building LuaJIT 2.0.1 ====
make -C src
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.s
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
CC        lj_char.o
BUILDVM   lj_bcdef.h
CC        lj_bc.o
CC        lj_obj.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_dispatch.o
CC        lj_vmevent.o
CC        lj_vmmath.o
CC        lj_strscan.o
CC        lj_api.o
CC        lj_lex.o
CC        lj_parse.o
CC        lj_bcread.o
CC        lj_bcwrite.o
CC        lj_load.o
CC        lj_ir.o
CC        lj_opt_mem.o
BUILDVM   lj_folddef.h
CC        lj_opt_fold.o
CC        lj_opt_narrow.o
CC        lj_opt_dce.o
CC        lj_opt_loop.o
CC        lj_opt_split.o
CC        lj_opt_sink.o
CC        lj_mcode.o
CC        lj_snap.o
CC        lj_record.o
CC        lj_crecord.o
BUILDVM   lj_recdef.h
CC        lj_ffrecord.o
CC        lj_asm.o
CC        lj_trace.o
CC        lj_gdbjit.o
CC        lj_ctype.o
CC        lj_cdata.o
CC        lj_cconv.o
CC        lj_ccall.o
CC        lj_ccallback.o
CC        lj_carith.o
CC        lj_clib.o
CC        lj_cparse.o
CC        lj_lib.o
CC        lj_alloc.o
CC        lib_aux.o
BUILDVM   lj_libdef.h
CC        lib_base.o
CC        lib_math.o
CC        lib_bit.o
CC        lib_string.o
CC        lib_table.o
CC        lib_io.o
CC        lib_os.o
CC        lib_package.o
CC        lib_debug.o
CC        lib_jit.o
CC        lib_ffi.o
CC        lib_init.o
AR        libluajit.a
CC        luajit.o
BUILDVM   jit/vmdef.lua
DYNLINK   libluajit.so
LINK      luajit
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function l_message:luajit.c(.text+0x24): error: undefined reference to 'zl_fprintf'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function l_message:luajit.c(.text+0x38): error: undefined reference to 'zl_fprintf'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function l_message:luajit.c(.text+0x44): error: undefined reference to 'zl_fflush'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function l_message:luajit.c(.text+0x54): error: undefined reference to 'zl_stderr'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function l_message:luajit.c(.text+0x60): error: undefined reference to 'zl_stderr'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function print_jit_status:luajit.c(.text+0x194): error: undefined reference to 'zl_fputs'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function print_jit_status:luajit.c(.text+0x1a0): error: undefined reference to 'zl_putc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function print_jit_status:luajit.c(.text+0x1ac): error: undefined reference to 'zl_fputs'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function print_jit_status:luajit.c(.text+0x1dc): error: undefined reference to 'zl_putc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function print_jit_status:luajit.c(.text+0x1fc): error: undefined reference to 'zl_stdout'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pushline:luajit.c(.text+0x254): error: undefined reference to 'zl_fputs'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pushline:luajit.c(.text+0x25c): error: undefined reference to 'zl_fflush'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pushline:luajit.c(.text+0x280): error: undefined reference to 'zl_fgets'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pushline:luajit.c(.text+0x32c): error: undefined reference to 'zl_stdout'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pushline:luajit.c(.text+0x330): error: undefined reference to 'zl_stdin'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function dotty:luajit.c(.text+0x8a8): error: undefined reference to 'zl_fputs'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function dotty:luajit.c(.text+0x8b0): error: undefined reference to 'zl_fflush'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function dotty:luajit.c(.text+0x92c): error: undefined reference to 'zl_stdout'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pmain:luajit.c(.text+0x9f0): error: undefined reference to 'zl_fprintf'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pmain:luajit.c(.text+0x9f8): error: undefined reference to 'zl_fflush'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pmain:luajit.c(.text+0x1234): error: undefined reference to 'zl_stderr'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: luajit.o: in function pmain:luajit.c(.text+0x125c): error: undefined reference to 'zl_stdout'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_load.o): in function reader_file:lj_load.c(.text+0x2c): error: undefined reference to 'zl_feof'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_load.o): in function reader_file:lj_load.c(.text+0x50): error: undefined reference to 'zl_fread'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_load.o): in function luaL_loadfilex:lj_load.c(.text+0x204): error: undefined reference to 'zl_fopen'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_load.o): in function luaL_loadfilex:lj_load.c(.text+0x250): error: undefined reference to 'zl_ferror'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_load.o): in function luaL_loadfilex:lj_load.c(.text+0x27c): error: undefined reference to 'zl_fclose'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_load.o): in function luaL_loadfilex:lj_load.c(.text+0x2d0): error: undefined reference to 'zl_fclose'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_load.o): in function luaL_loadfilex:lj_load.c(.text+0x364): error: undefined reference to 'zl_stdin'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_aux.o): in function panic:lib_aux.c(.text+0x48): error: undefined reference to 'zl_fputc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_aux.o): in function panic:lib_aux.c(.text+0x54): error: undefined reference to 'zl_fputc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_aux.o): in function panic:lib_aux.c(.text+0x74): error: undefined reference to 'zl_stderr'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_vmevent.o): in function lj_vmevent_call:lj_vmevent.c(.text+0x19c): error: undefined reference to 'zl_fputc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_ir.o): in function lj_ir_callinfo:lj_ir.c(.data.rel.ro+0x88): error: undefined reference to 'zl_fputc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_ir.o): in function lj_ir_callinfo:lj_ir.c(.data.rel.ro+0x90): error: undefined reference to 'zl_fwrite'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_clib.o): in function lj_clib_load:lj_clib.c(.text+0x378): error: undefined reference to 'zl_fopen'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_clib.o): in function lj_clib_load:lj_clib.c(.text+0x390): error: undefined reference to 'zl_fgets'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_clib.o): in function lj_clib_load:lj_clib.c(.text+0x3c4): error: undefined reference to 'zl_fgets'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_clib.o): in function lj_clib_load:lj_clib.c(.text+0x3e8): error: undefined reference to 'zl_fclose'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lj_clib.o): in function lj_clib_load:lj_clib.c(.text+0x43c): error: undefined reference to 'zl_fclose'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_base.o): in function lj_cf_print:lib_base.c(.text+0x128): error: undefined reference to 'zl_putc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_base.o): in function lj_cf_print:lib_base.c(.text+0x140): error: undefined reference to 'zl_fwrite'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_base.o): in function lj_cf_print:lib_base.c(.text+0x1d4): error: undefined reference to 'zl_putc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_open:lib_io.c(.text+0x6c): error: undefined reference to 'zl_fopen'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_readline:lib_io.c(.text+0x248): error: undefined reference to 'zl_fgets'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x2b4): error: undefined reference to 'zl_clearerr'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x2e0): error: undefined reference to 'zl_ferror'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x34c): error: undefined reference to 'zl_getc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x360): error: undefined reference to 'zl_ungetc'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x3f4): error: undefined reference to 'zl_fread'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x440): error: undefined reference to 'zl_ferror'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x4cc): error: undefined reference to 'zl_fread'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_read:lib_io.c(.text+0x514): error: undefined reference to 'zl_fscanf'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_write:lib_io.c(.text+0x700): error: undefined reference to 'zl_fwrite'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_write:lib_io.c(.text+0x744): error: undefined reference to 'zl_fprintf'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_write:lib_io.c(.text+0x790): error: undefined reference to 'zl_fwrite'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function lj_cf_io_open:lib_io.c(.text+0x83c): error: undefined reference to 'zl_fopen'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function lj_cf_io_popen:lib_io.c(.text+0x8c8): error: undefined reference to 'zl_popen'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_close:lib_io.c(.text+0xa04): error: undefined reference to 'zl_pclose'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function io_file_iter:lib_io.c(.text+0xa90): error: undefined reference to 'zl_ferror'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function lj_cf_io_method_setvbuf:lib_io.c(.text+0xca8): error: undefined reference to 'zl_setvbuf'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function lj_cf_io_tmpfile:lib_io.c(.text+0xf04): error: undefined reference to 'zl_tmpfile'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_io.o): in function luaopen_io:lib_io.c(.text+0x1064): error: undefined reference to 'zl_stdin'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_os.o): in function lj_cf_os_rename:lib_os.c(.text+0x728): error: undefined reference to 'zl_rename'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_os.o): in function lj_cf_os_remove:lib_os.c(.text+0x75c): error: undefined reference to 'zl_remove'
/Users/mkinoshita/android-ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: libluajit.a(lib_debug.o): in function lj_cf_debug_debug:lib_debug.c(.text+0x1cc): error: undefined reference to 'zl_stdin'
collect2: ld returned 1 exit status
make[1]: *** [luajit] Error 1
make: *** [default] Error 2
```

**Comment by makotok** [comment]
switching of header files or do not need?

```
    MY_HEADER_SEARCH_PATHS += $(MY_MOAI_ROOT)/3rdparty/lua-5.1.3/src
```

**Comment by CircuitCipher** [comment]
The errors occur during the linking of the luajit executable which is not used .  You should be able to continue with the build because the libraries build successfully. It's detailed in the luajit forum post.  Maybe there is a way to get the luajit build system to only build the libraries.

We don't need to switch the headers as the JIT and lua interface we use are compatible.

**Comment by CircuitCipher** [comment]
I will look into updating the luajit build to not build the executable.  While I do that,  can you continue to test?  If you run the build again it will detect the previously built libraries and should work.

**Comment by makotok** [comment]
I worked fine in Android.
However, error is output is not good.
People who saw first will be surprised.

**Comment by CircuitCipher** [comment]
I agree.  I just wanted the rest of the changes reviewed while I figure out the few remaining issues.  I will be looking at the luajit executable issues tonight.

**Comment by CircuitCipher** [comment]
@makotok The latest changes prevent the errors by only building the libraries.

**Comment by makotok** [comment]
Thank you.

**Pull request merged**
