### PR TITLE
fixed android build; webp and NEON on android; removed duplicate sources in xcode builds

### PR DESCRIPTION
**Pull request by patrickmeehan**

### CODE REVIEW

**Comment by moai-sdk** [comment]
failure

**Comment by ConghuZhao** [comment]
retest

**Comment by moai-sdk** [comment]
started
failure

**Comment by moai-sdk** [comment]
Build finished. No test results found.
failure

**Comment by moai-sdk** [comment]
failure

**Comment by moai-sdk** [comment]
started
failure

**Comment by moai-sdk** [comment]
Build finished. No test results found.
success

**Comment by moai-sdk** [comment]
success

**Comment by moai-sdk** [comment]
started
failure

**Comment by moai-sdk** [comment]
Build finished. No test results found.
success

**Comment by moai-sdk** [comment]
success

**Comment by moai-sdk** [comment]
started

**Comment by moai-sdk** [comment]
Build finished. No test results found.

**Comment by moai-sdk** [comment]
Build Success

**Comment by moai-sdk** [comment]
Build Failure

**Comment by moai-sdk** [comment]
Build Failure

**Comment by moai-sdk** [comment]
Build triggered. sha1 is merged.

**Comment by moai-sdk** [comment]
Build started sha1 is merged.
Build Failure

**Comment by moai-sdk** [comment]
Build Failure

**Comment by moai-sdk** [comment]
Build Failure

**Comment by moai-sdk** [comment]
Build Failure

**Comment by moai-sdk** [comment]
Build Success

**Comment by moai-sdk** [comment]
Build Success

**Comment by moai-sdk** [comment]
Build Success

**Comment by moai-sdk** [comment]
Build Success

**Comment by moai-sdk** [comment]
Build Success

**Comment by moai-sdk** [comment]
Build Failure

**Comment by moai-sdk** [comment]
Build IOS Failure

**Comment by moai-sdk** [comment]
Build Android Failure

**Comment by moai-sdk** [comment]
Build OSX  Failure

**Comment by moai-sdk** [comment]
Build Failure

**Comment by moai-sdk** [comment]
Build OSX  Failure

**Comment by ConghuZhao** [comment]
retest this please

**Comment by moai-sdk** [comment]
Build Android Success

**Comment by moai-sdk** [comment]
Build IOS Failure

**Comment by moai-sdk** [comment]
Build OSX  Failure

**Comment by moai-sdk** [comment]
Build Android Failure

**Pull request closed without merging**
