### PR TITLE
It dramatically improves the performance of Android.

### PR DESCRIPTION
**Pull request by makotok**
I have dramatically improved the performance of Android host.
I also improved the behavior of the keyboard.
- Move GLThead the update process.
- Fixed a bug of the keyboard.
- Specify improvement of orientation
- Improvement of indentation.

### CODE REVIEW

**Comment by CircuitCipher** [comment]
In the future, you may want to keep the code formatting changes in separate commits from the actual feature work.  It makes it easier to read the changes.  Thank you for your work on this.  I will hopefully have time this weekend to test this out.

It looks like Scottwb has already tried it and has had good results.  http://getmoai.com/forums/android-gfx-performance-boost-t2019/

**Comment by tangzero** [comment]
Great!

**Comment by makotok** [comment]
Sorry.
I have modified format because was not good too.

**Comment by CircuitCipher** [comment]
I checked this out locally and had an issue.  When attempting to login with Facebook I get the following exception:

```
/AndroidRuntime(10822): FATAL EXCEPTION: GLThread 9
E/AndroidRuntime(10822): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
E/AndroidRuntime(10822):    at android.os.Handler.<init>(Handler.java:121)
E/AndroidRuntime(10822):    at android.app.Dialog.<init>(Dialog.java:112)
E/AndroidRuntime(10822):    at com.facebook.android.FbDialog.<init>(FbDialog.java:62)
E/AndroidRuntime(10822):    at com.facebook.android.Facebook.dialog(Facebook.java:780)
E/AndroidRuntime(10822):    at com.facebook.android.Facebook.startDialogAuth(Facebook.java:309)
E/AndroidRuntime(10822):    at com.facebook.android.Facebook.authorize(Facebook.java:207)
E/AndroidRuntime(10822):    at com.facebook.android.Facebook.authorize(Facebook.java:126)
E/AndroidRuntime(10822):    at com.ziplinegames.moai.MoaiFacebook.login(MoaiFacebook.java:134)
E/AndroidRuntime(10822):    at com.ziplinegames.moai.Moai.AKUUpdate(Native Method)
E/AndroidRuntime(10822):    at com.ziplinegames.moai.Moai.update(Moai.java:458)
E/AndroidRuntime(10822):    at com.company.application.MoaiView$MoaiRenderer.onDrawFrame(MoaiView.java:177)
E/AndroidRuntime(10822):    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1339)
E/AndroidRuntime(10822):    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1123)
```

**Comment by makotok** [comment]
Thank you for testing.
Would because I've moved to GLThread from MainThread.

Place to fix this are many.
However, this modification would be necessary.
I will fix this.

**Comment by CircuitCipher** [comment]
Okay great, thank you.  This may also be a problem with the Android Twitter.  I haven't tested that yet.  I'll take a look when I get a chance.

**Comment by CircuitCipher** [comment]
Great, I'll try to test out these new changes tonight.

**Comment by makotok** [comment]
I'm sorry, place does not need to be modified also included.
I redo the part. I ask you for a check again.

**Comment by CircuitCipher** [comment]
Thanks for the updates @makotok.  I tested and both Facebook and Twitter are working.  This is a big change and I am concerned about breaking other extensions.  I see there are:
- "Android Intents" being used in google-billingv3 and google-billing
- Tapjoy show offers may launch a new activity?

Could you verify that similar changes are not needed in these other extensions?  Thanks.  I apologize I'm short on time today.  If I wasn't I would help more in identifying the locations of those changes.

**Comment by makotok** [comment]
Thank you for testing.

I confirmed the implementation of Android.
The processing that must be performed on the UI thread are as follows.
- Operation of a class that inherits the View
- Generate the Handler and do not specify a Looper

Activity.startActivity works.
MOAIMoviePlayer worked.
This is also accessed from other threads to run in MainThread.

It's a problem in a multi-thread, according to ViewRootImpl.checkThread.
It is an error for which you have checked the thread in this process.

This pull request is a big correction.
However, the benefits would be greater than the risk.

**Comment by makotok** [comment]
@seclorum 
Where necessary are as follows.
- Call of AKU function
- Where concurrent access is an issue

If you move to the UI thread, there is no problem if you synchronize the AKU function.

**Comment by CircuitCipher** [comment]
Okay well if we run into issues, we know where to look.  Merging.

**Comment by makotok** [comment]
Thank you!

**Pull request merged**
