### PR TITLE
Fixed VSYNC issue on OSX.

### PR DESCRIPTION
**Pull request by clementfarabet**
The default host had no VSYNC on OSX, this patch fixes that.

### CODE REVIEW

**Comment by frantufro** [comment]
Do you think you can cherry pick what you pull in order to avoid the merge? So we can only merge the important commit?? 
Thanks a lot!

**Comment by clementfarabet** [comment]
Sorry about that, I went a bit too fast... redoing it in a sec.

**Comment by frantufro** [comment]
Don't worry!! It's just to avoid having strange commits in there. :) 
Thanks a lot for collaborating! This is an important commit, I'd love to have it though!

**Comment by frantufro** [comment]
In fact, don't close it, let's just upgrade it. :)

**Comment by clementfarabet** [comment]
Ah, I have the commit ready on my side, how can I upgrade it?

**Comment by frantufro** [comment]
I can't reopen this pull request.
Just go ahead and create a new one. :)

Thanks a lot!

**Comment by clementfarabet** [comment]
OK just opened a new one, all clean!

**Pull request closed without merging**
