### PR TITLE
Update iOS Xcode project

### PR DESCRIPTION
**Pull request by PeqNP**
Update the Xcode project to use the new "improved" method for including image resources.

These changes include updates to how the app icon and launch resources are included in the project. These changes also reduce the compile time for subsequent builds to a few seconds if ccache is installed.
- AppIcon is now in Images.xcassets
- Launch icon is now in Images.xcassets
- Now uses LaunchScreen.xib to reduce the amount of assets required by project to a single image
- Introduced ccache to all libmoai targets as well as both the moai-ios and moai-ios-static projects. This reduces build times to a few seconds after the first build. You must have ccache installed to use this feature. If ccache is not found, it falls back to the default compiler.

Lastly, I have set both projects to always require fullscreen and to hide the status bar. The supported orientations have also been set to portrait and both landscape orientations. Obviously these can be changed. I believe these settings seem reasonable, giving that the projects used by MOAI are primarily games.

### CODE REVIEW

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by PeqNP** [comment]
test

**Comment by halfnelson** [comment]
test

**Comment by seclorum** [comment]
test

**Comment by ConghuZhao** [comment]
test

**Comment by seclorum** [comment]
I'm not seeing any reason not to merge this.  Objections to just doing it?  Would make life easier for new recruits.

**Pull request merged**
