### PR TITLE
Fancy Glut Host

### PR DESCRIPTION
**Pull request by sclark39**
This change makes it so the glut host works the same as the love2d executable. You can drop a directory on it, an archive, or a script and have it run. You can also create a fused exe with 'copy /b moai.exe+src.zip game.exe' and it will run (and the created fused exe will ignore any other parameters passed to it).

I am not sure if the code in the aku_modules file needs to be wrapped in some #ifdef GLUTHOST or something, or if the code should be moved elsewhere. Please advise.

### CODE REVIEW

**Comment by halfnelson** [comment]
Your commit 3955742 should be cherry picked into a branch based off develop so that this can merge cleanly. This pull is dragging in all the differences from 1.5 -> develop and not just your proposed addition. Let me know if you need help with cleaning up the pull.

**Comment by sclark39** [comment]
I can do so. I wanted to make sure there was interest in this work and that it was implemented properly first.

**Comment by patrickmeehan** [comment]
@sclark39, I haven't had time to look at the code, but it sounds great from the description. That said, we are trying to move from GLUT to SDL. (Or at least I am.) Do you think it would be possible to bring these features into the SDL host and use that moving forward?

Anyway, am going to close this since we can't auto-merge (and it looks like there are some new cherry-picked pull requests from you).

Thanks!

**Comment by sclark39** [comment]
Is there a VS project for the SDL host?

**Comment by patrickmeehan** [comment]
There is, but it's rusty. If you use either 2008 or 2010 and have time would be awesome if you want to update it. There are remnants on my fork of the repo.

Or... it's high on my list to bring those back, if you don't mind waiting a week or two. :)

**Comment by sclark39** [comment]
I'm happy to wait. :)

**Comment by halfnelson** [comment]
Ah, that would explain why they don't build for me. I am working on getting
them back up and going as part of the 1.5 merge into develop (well at least
getting it building on windows again)

**Pull request closed without merging**
