### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by patrickmeehan**
- fix for regression in MOAICoroutine's setDefaultParent
- fix for dangerous edge case in MOAIFileSystem's deleteDirectory (found by @halfnelson)

More stuff. Lots of stuff and little fixes.

### CODE REVIEW

**Comment by ConghuZhao** [comment]
test

**Comment by ConghuZhao** [comment]
test

**Comment by PeqNP** [comment]
Is the only thing preventing this pull request from being pulled in is that it is failing building for Linux?

**Comment by halfnelson** [comment]
looks like that linux build is never going to finish,something is wrong with the trigger maybe? details refers to $BUILDNUMBER so maybe that is a clue

**Pull request closed without merging**
