### PR TITLE
openssl 1.0.0m see #940

### PR DESCRIPTION
**Pull request by halfnelson**
upgrade of third party openssl to 1.0.0m, cleanup platform includes. see https://github.com/moai/moai-dev/issues/940

### CODE REVIEW

**Comment by romainmoreau** [comment]
Thanks for the quick fix !
As stated, it builds and runs fine on Android.
However, the vs2013 projects don't build anymore.

**Comment by halfnelson** [comment]
Typical. Tested on mingw, ios, android, osx and linux. Forgot that visual studio is kind of its own platform. Working on a fix now

**Comment by halfnelson** [comment]
ok, compiles for me now in vs2012

**Comment by makotok** [comment]
Thank you everyone!

**Comment by romainmoreau** [comment]
Thanks, it works great with vs2013 too.

**Pull request merged**
