### PR TITLE
Fix for gfx state bug (black textures)

### PR DESCRIPTION
**Pull request by Vavius**
Bug is revealed only when disabling debug draw on layer.

### CODE REVIEW

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by ConghuZhao** [comment]
test

**Pull request merged**
