### PR TITLE
Feature dump Sep 23; revised Lua binding, SDL, misc

### PR DESCRIPTION
**Pull request by patrickmeehan**
Sorry for the huge pull request. One of the challenges of the git workflow is that sometimes smaller pull requests on their own branches can't get merged in before I've taken back into my own development branch and continued work. It's not feasible for me to have a bunch of little feature branches waiting around - there are often inter-dependencies. So it's going to be monolithic pull requests more often the not.

This one is going to break some stuff. Here's a quick rundown of the breaky parts:
- I'm tired of *glut and moving to SDL. Decided to build SDL as a static lib which is supported on OSX but not so much on Windows. To that end I commented out a big chunk of SDL_stdlib.c. I'm sure there's a better solution through compiler settings and header substitution; I just didn't have time.
- The new SDL host is _minimal_. I'll add more features as I need them. Hoping the community will fill in the rest.
- Have not tried running the revised test runner host. Not sure if this was ever added to CI or used for anything.
- I built Xcode OSX but didn't have time for the iOS sample project. Am hoping someone volunteers to fix it up.
- I changed the naming scheme for the modules to clarify the initialization/finalization process. It used to be that 'app' initialization was implicit, but this led to asymmetry of calls in the host (even though it handled all cases). This bugged me, so I made it more explicit. Each module now has an app initialize/finalize and a context intitialize/finalize. (Didn't have time to do the mobile modules - just desktop/windows so far).
- I've added some helper files for the 'official' Moai host modules. They are under the 'host-modules' folder. This is still a little half-baked, but the idea is to make some of the host tedium reusable and hide a lot of the ugly #ifdef's.

Some important fixes/changes:
- I did a lot of work on the Lua binding as it pertains to GC. Still not sure if we are out of the woods, but the intermittent crashes I was seeing in out game have gone away.
- MOAISim now takes control of the GC when it starts running. So business as usual until the first sim loop, then collectgarbage gets replaces with a warning and MOAISim starts running the GC incrementally. This let me get rid of a bunch of release/retains in the dep graph and action tree update code.
- The engine-to-Lua lifecycle was improved and now correctly provides a ref table to singleton classes so Lua objects created inside of constructors should now be exposed to Lua correctly.
- I added a way to set a custom GC callback on Moai objects for debugging purposes (dangerous - use with care). Also added a flag on MOAILuaRuntime to log GC events.
- The new build settings on Xcode for iOS and OSX did _not_ respect the implementation of the VFS via injection of zl_replace.h. This has been fixed. In the process I had to break zlcore into two libraries as zl-vfs is not supposed to have zl_replace.h injected. This is pretty darn important as the VFS will silently fail without this change.
- I added a flag to MOAIAction to disable its auto-stop on no children. The default keeps the original behavior.

I am starting some new projects that are going to add features to Moai SDK. I know this pull request is a pain, but if we can get it integrated, fixed and building that will pave the way for what's to come. Thanks!

### CODE REVIEW

**Comment by CircuitCipher** [comment]
Its very tough to merge xcode project files.  You can see a naive quick pass of a merge of this PR here: https://github.com/moai/moai-dev/tree/patrickmeehan-feature/09-23-13

One thing to note is that the recent JIT stuff didn't come through.  Maybe you can try to pull from upstream development again so that its added in?

@makotok and @superquadratic I think we are going to need some more people looking at this.

EDIT:  My second attempt caused the xcode projects to be not parsable.  Much fun to be had.

**Comment by CircuitCipher** [comment]
I almost feel as though the commits need to be cherry picked (http://wiki.koha-community.org/wiki/Using_Git_Cherry_Pick) and merged separately to prevent huge devastation.  That would require some serious time investment though.

**Comment by patrickmeehan** [comment]
Yeah, the Xcode stuff is pretty much a nightmare. But that's probably the main challenge. If I had time my approach would probably be to undo my Xcode work, grab the latest w/ LuaJIT then redo what I added. The main things to capture are the separation of zlcore into two libs (to support VFS) and the addition of SDL on OSX.

**Comment by makotok** [comment]
Many modifications have been made very.
Confirmation is difficult in this.

1)
I tried to operate Build.
It was operated samples Hanappe process but fall immediately.

https://github.com/makotok/Hanappe

It looks compatible as lost significantly.

2)
Development branch of the current is fairly stable.
First, I want you to release the MoaiSDK V1.5.
I make a big effort to then.

3)
I think it is better to commit to correct a little bit at a time is good.
It is not able to merge in this.

It will break substantially when you merge.

4)
I think if you expect a modification of someone, you might want to create a branch directly to the moai repository is good.
We can be performed additional modifications.

**Comment by patrickmeehan** [comment]
Thanks, Makoto. These changes are live in our game now. Unfortunately I cannot do incremental commits as I have a crushing workload and cannot wait for gradual integration or keep featured pieced out into small branches. You can release 1.5 without these commits if you want.

MOAILuaObject works for me. Can you send me a small repro script demonstrating the error? I looked at line 502 but it is different from what is in the final implementation. I would not expect earlier commits in this chain to work on their own.

**Comment by makotok** [comment]
I have put the results and source below.

https://gist.github.com/makotok/6716797

I understood to some extent.
compatibility is lost for the structure of the metatable has changed.

However, the structure of the meta-table clean.
I think it has evolved.

1)old lua object

getmetatable(user_data)
-->memberTable

getmetatable(memberTable)
-->refTable

refTable.__index
-->interfaceTable

2) new lua object

getmetatable(user_data)
-->refTable

getmetatable(refTable)
-->memberTable

getmetatable(memberTable)
-->interfaceTable

interfaceTable.__index
-->interfaceTable

**Comment by makotok** [comment]
Some method names have changed.

```
MOAISim.forceGarbageCollection()
MOAISim.forceGC()
```

I think it ought not to be changed easily the method name and class that you exposed once.
If you want to change, to be deprecated.
Or updating the major version. (V1.5--> V2.0)

**Comment by makotok** [comment]
I would like to release the V1.5.
Is there a procedure for binary release?

After that, I want to merge by verifying this fix.
It's a significant modification, but it is attractive.

**Comment by patrickmeehan** [comment]
Makoto - the CI server is _supposed_ to automatically produce a release when you push to the 'publish' branch. That said, I don't know if it's ever been tested or used.

Who is maintaining the CI server right now? If no one, who wants to volunteer? :)

**Comment by makotok** [comment]
I refer to the Wiki.
May be pushed to the first, 'staging'?
When operating with a certain extent, to push the 'publish'?

https://github.com/moai/moai-dev/wiki/Ci-server-and-release-process-requirements

**Comment by makotok** [comment]
Anyway, I was merged into master branch from the development branch.
Also, just in case, I have created a V1.5a branch.

it safe to merge the development branch.
Because conflict has occurred, correction would be necessary some.

I work on validation for a while.

**Comment by makotok** [comment]
I merged to try.

https://github.com/moai/moai-dev/tree/merge-pr787

Behavior is strange some.

1)
It is a fast FPS is tremendous.
Is not working well?

```
print(MOAISim.getPerformance())
-->3823.7485351562
```

**Comment by Vavius** [comment]
@patrickmeehan, @makotok, @joshua-jandyco 
Any updates on this? 
Again we are having many conflicting forks out there with outdated main repo...

**Comment by makotok** [comment]
Merge is nearly impossible anymore.

In addition, Patrick has many modifications by fork repository.
Does not make much sense to merge the fix this pull request?

**Comment by ibisum** [comment]
> Merge is nearly impossible anymore.
> In addition, Patrick has many modifications by fork repository.
> Does not make much sense to merge the fix this pull request?

The sooner we can get a decent head to start working from, with some of these great fixes, the better.  Its becoming a headache to maintain many branches!

j.

**Comment by superquadratic** [comment]
Searching for a fix to a garbage collection crash, I just spent 2 days going through these changes. Here's what I found out so far:
- There are some valuable fixes to Lua GC handling in the fix/lua-gc branch: patrickmeehan/moai-dev@0d4a40eec108afd18f544af373d1e26ef7916325. I ended up merging them into my game's branch, with the following additional fixes for iOS: theGoodEvil/moai-dev@be140ff1f91671e20c5fefd4ee4be1cc0e835b86, theGoodEvil/moai-dev@6b2c2b8474da9a2f25eef90d436caabaf4300f82
- Later Lua memory management changes (from @patrickmeehan's feature/mem-overhaul branch) break @makotok's flower library that uses MOAILuaObject:setInterface() to add additional functions to a userdata object.
- The GLUT host is translated half-way to freeglut, leaving it in a broken state. freeglut does not seem to be a good idea to me, since it does not support OS X without using X11.
- The MobileAppTracking framework does not seem to work with Xcode 5 / OS X 10.9.
- The same goes for LuaJIT.

I suggest the following steps to continue:
- Merge patrickmeehan/moai-dev@0d4a40eec108afd18f544af373d1e26ef7916325 and the additional iOS fixes into master. Fix compatibility with Xcode 5 / OS X 10.9 and call it V1.5. (With or without an official release.)
- Merge this whole thing into development. Resolve the Xcode projects "using theirs", i.e. overwriting the changes on development using the ones from the PR. Then, step by step, fix or reenable:
  - GLUT host
  - flower library / setInterface()
  - MobileAppTracking, Twitter, PlayHaven
  - LuaJIT
- Get the CMake build system to work on all platforms and abandon (i.e. get rid of) all platform-specific build scripts (Xcode, Visual Studio etc.). I went nuts trying to merge or redo changes to the Xcode projects, or just understand who changed what (and why).

It's not going to be easy, but I think there's no way around merging this stuff, since it contains a lot of valuable changes and is the basis for future contributions from @patrickmeehan and the rest at Zipline.

**Comment by ibisum** [comment]
> It's not going to be easy, but I think there's no way around merging this stuff, since it contains a lot of valuable changes and is the basis for future contributions from @patrickmeehan and the rest at Zipline.

Agreed - there is no easy way out of this mess but to merge ahead and deal with the bugs.

j.

**Pull request merged**
