### PR TITLE
updated MOAIPartition propForPoint parameters

### PR DESCRIPTION
**Pull request by patrickmeehan**
...to match the form of the other spatial queries

### CODE REVIEW

**Comment by moai-sdk** [comment]
Build IOS Success

**Comment by moai-sdk** [comment]
Build Android Success

**Comment by moai-sdk** [comment]
Build OSX  Success

**Comment by moai-sdk** [comment]
Build Android Success

**Comment by moai-sdk** [comment]
Build IOS Success

**Comment by moai-sdk** [comment]
Build OSX  Success

**Comment by moai-sdk** [comment]
Build IOS Failure

**Comment by moai-sdk** [comment]
Build OSX  Failure

**Comment by moai-sdk** [comment]
Build Android Success

**Comment by moai-sdk** [comment]
Build IOS Success

**Comment by moai-sdk** [comment]
Build IOS Success

**Comment by patrickmeehan** [comment]
retest this please

**Comment by ConghuZhao** [comment]
retest this please

**Pull request closed without merging**
