### PR TITLE
updates the facebook SDK for Android, samples and iOS coming soon

### PR DESCRIPTION
**Pull request by iamricard**

### CODE REVIEW

**Comment by iamricard** [comment]
I will commit the samples to this pull request, so don't merge yet!

**Comment by iamricard** [comment]
Could someone take a look at this and see if it can be merged? Works fine on our build and we would rather work with the main repo than a fork.

/cc @halfnelson @patrickmeehan @joshua-jandyco

**Comment by halfnelson** [comment]
There seemed to be a few files with whitespace only changes. Merging these in can cause unwanted conflicts and dirties the history a little. It would be great if only the essential changes for this to work were added. 

Thanks for the pull request although I am not a repo maintainer and cannot do merges

**Comment by iamricard** [comment]
@halfnelson except for the JniUtils and build.sh everything is near-complete rewrite of the modules. 
**Edit**: there is pull from two days later fixing the build.sh amongst other things. About whitespace, I don't really know how to "fix" it without having to manually add trailling whitespace everywhere.

**Comment by halfnelson** [comment]
nevermind then, whoever does the merge can just ignore the whitespace changes

**Pull request closed without merging**
