### PR TITLE
Revert "MOAIGraphicsProp: Invoke draw with proper index"

### PR DESCRIPTION
**Pull request by ciwrl**
This reverts commit d503653496fff0205bddc6665a7b6d1a43835ca1.

### CODE REVIEW

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch? Type 'test' in a comment to start test.

**Comment by ciwrl** [comment]
Caused regressions outside of intended fix, should be backed out.

**Comment by patrickmeehan** [comment]
I believe this is fixed on the partner/pi-develop branch already

**Pull request closed without merging**
