### PR TITLE
Test git plugin

### PR DESCRIPTION
**Pull request by ConghuZhao**
test

### CODE REVIEW

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch?

**Comment by ConghuZhao** [comment]
ok to test

**Comment by moai-sdk** [comment]
Can one of the admins verify this patch?

**Comment by ConghuZhao** [comment]
ok to test

**Comment by ConghuZhao** [comment]
test this please

**Comment by ConghuZhao** [comment]
retest this please

**Comment by moai-sdk** [comment]
success

**Comment by moai-sdk** [comment]
success

**Pull request closed without merging**
