### PR TITLE
Fixes moai not supporting sockets, sqlite3 and others on Linux

### PR DESCRIPTION
**Pull request by dleslie**
Added necessary changes to get luaext working under Linux in order to support RapaNui.

Includes a FindSQLite3 module from the 'net that's licensed under BSD.

### CODE REVIEW

**Comment by systemrok** [comment]
Thanks for contributing. Can you please review and sign the contributors agreement? http://getmoai.com/open-source-contributions.html

**Comment by dleslie** [comment]
I haven't a scanner or a fax machine readily available, it will be a few
days.

-Dan

**Comment by dleslie** [comment]
Sorry, work has been insane.

**Comment by makotok** [comment]
This pull request or still valid? 
I can not merge anymore. 

This pull request once closed.

**Pull request closed without merging**
